### ISSUE TITLE
ReadMe: Update the Introduction Pitch

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#70]
An introduction pitch needs to be an elevated pitch. I have discussed about the project in these two places:

- [Intro Video](https://rb.gy/cygmlf)
- [BrainStorming Day 1: Project Plan](https://rb.gy/dfxjnd)

Can we have an awesome pitch about the project introduction? The current Introduction section contains the description of the project. We need a story telling way of writing the pitch. Any ideas? Let's discuss! 🤘🏻

Up for grabs! ✋🏻

**Comment by Venkatesh-tech** [comment]
Hey sir @praveenscience, I'm a beginner and would like to contribute to this project

I will discuss the following
 1.Platform Agenda
 2.Who can use this platform
 3.How onboarding is made easy with this platform
 and more......

**Comment by praveenscience** [comment]
@Venkatesh-tech Great man. Would you like to pick this up then? ✋🏻

**Comment by Venkatesh-tech** [comment]
Yes, I love to work on this issue and I will try to give the best 
Please assign this to me...

**Comment by praveenscience** [comment]
It's yours @Venkatesh-tech

**Comment by Venkatesh-tech** [comment]
Please review it and inform me of necessary changes. so that I can make a PR
I will give my word that I will keep things updated as we come up with new ideas.

### Intro :
The plight of small and medium companies has gravely wounded the world with serious consequences impacting all the onboard new interns, developers, full-time roles, and individuals during their recruitment phase. To solve these issues and to show a brilliant path to all the individuals listed we proudly present **DevTernShip**, a platform for Internship OnBoarding, projects recruiting, and many more... for students, interns, developers who are looking actively for Internship roles, full-time roles at the moment.

### Agenda:
We are on the mission of resolving a crisis for a lot of small and medium enterprises, who are trying to recruit interns for their projects. This platform aims to onboard new interns, who have applied to the companies and help them understand the process and make the transition smooth. This platform is the best gateway to show recruiters what interns are capable of.

### Easy onboarding:
In this program we are going to have a setup for every individual intern by providing their account section i.e; Profile likely and show others that you are ready to work on a particular stack by joining their company as an Intern. To guide you better, we are also planning to introduce Learning pages, Application Tracking systems, an Opportunity tracker, and live interactive sections on Youtube by Our well-qualified mentors to keep you Updated.

### Bridging the gap:
This program helps the Intern to interact with the Recruiter effectively by providing social media handles and also interns get a chance of exhibiting their work by sharing their Github, LinkedIn profiles to their recruiters

**Comment by praveenscience** [comment]
Go on, raise a PR. Looks damn good! ❤️
